### PR TITLE
Using fs-copy-file-sync over fs.copyFileSync for backwards compatability

### PR DESCRIPTION
**Pull request by TylerBre**

### CODE REVIEW

**Comment by SpyBot68** [comment]
ok interesting, so would correcting the same lines on my end work as a fix? or there are probably additional steps...

**Comment by TylerBre** [comment]
@SpyBot68 this is just for getting backwards compatability working with car/track upload.

**Comment by TylerBre** [comment]
@Pringlez confirmed working car/track uploading with node v4.9.1

**Review by Pringlez — APPROVED** [review]
Nice job, tested it locally. Seems to be fine :+1:

**Pull request merged**
