### PR TITLE
add help page

### PR DESCRIPTION
**Pull request by surtic86**
help page with default server config and explanation of the settings

### CODE REVIEW

**Comment by Cele91** [comment]
To prevent this, I have add title="" for every voice. Good work in any case :) However, the restart button must be repaired because it does not work and the items with check should receive two clicks to activate. and, can also enter a chance to overshadow the port fields, so that they can not change?

**Comment by surtic86** [comment]
You have? Where? Haven't seen it. But yes we can do the Help for every Setting in a Tooltip directly.

For the rest you should open a Issue for each that we can fix it.

**Comment by Cele91** [comment]
The changes have I created for my own because I do not know how to publish here. Same for the fixes required, I am not capable and I apologize for incompetence

**Comment by surtic86** [comment]
Ah okey, then let me help / explane it how you can do this. Better we don't do this here. Send me a Message on https://keybase.io/surtic86 or surtic86@gmail.com

**Comment by Pringlez** [comment]
Good stuff! 👍

**Pull request merged**
